### ISSUE TITLE
Possible bugfix / speed boost

### ISSUE THREAD

**Issue by dlwyatt** [ctrlbold/modules#1]
Hi @ctrlbold :)  I was just looking over the latest version of Test-SqlImportSpeed, and line 515 (`$datatable = $datatable.Clone()`) jumped out at me as being a potential bug.  You're calling Clone() on the same DataTable object that you've just populated and passed to the background thread, and I'm not certain what state it will be in when that happens.  (Will it still contain any rows?  If so, does the script waste time importing the same rows twice?  etc.)

The idea was to maintain a separate, empty DataTable object with the columns initialized, and clone that after passing the populated one off to a background thread.  It's a small change that might have a pretty decent impact on speed and reliability:

``` posh
# Around line 453, just after setting up the columns on the $dataTable object:

$emptyDataTable = $dataTable.Clone()

# Line 515:

$dataTable = $emptyDataTable.Clone()
```

**Comment by potatoqualitee** [comment]
Hey Dave,
Thanks for the note! I chose clone because it copies the structure (so I won't have to recreate columns), but not the data. 

Microsoft states: Clone creates a new DataTable with the same structure as the original DataTable, but does not copy any data (the new DataTable will not contain any DataRows). To copy both the structure and data into a new DataTable, use Copy.

I'll reexplore this, though. Perhaps it'll be better at releasing memory if I use a totally different object to clone (unlikely, but I'm desperate ;)

**Comment by dlwyatt** [comment]
Ah, okay!  I should RTFM first; I was making the assumption that Clone() was copying data.  If not, then it should be fine as-is.  :)
